name: networkautomation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  im_stepper:
  shared_preferences:
  firebase_auth:
  cloud_firestore:
  firebase_core:
  firebase_storage:
  fluttertoast:
  flutter_bloc:
  flutter:
    sdk: flutter
  cupertino_icons:
  intl: ^0.19.0
  file_picker: ^8.0.0+1
  html: ^0.15.4
  http: ^1.2.1
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/