// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyjxLkiimHBp4VC8hJukAw65lVSHVF6CE',
    appId: '1:270817397728:web:7c58ff81cd3e586d343985',
    messagingSenderId: '270817397728',
    projectId: 'auto-networks',
    authDomain: 'auto-networks.firebaseapp.com',
    storageBucket: 'auto-networks.appspot.com',
    measurementId: 'G-LGWL6PDNM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3_ixi3vmlzAlQXF9-eA_G_bvKbRIexAs',
    appId: '1:270817397728:android:ed4a24935122498e343985',
    messagingSenderId: '270817397728',
    projectId: 'auto-networks',
    storageBucket: 'auto-networks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQMOJUqMhofquYEkwLh_obqVYuw96kPs',
    appId: '1:270817397728:ios:9ce1bcd5c969f5d6343985',
    messagingSenderId: '270817397728',
    projectId: 'auto-networks',
    storageBucket: 'auto-networks.appspot.com',
    iosBundleId: 'com.example.networkAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQMOJUqMhofquYEkwLh_obqVYuw96kPs',
    appId: '1:270817397728:ios:e22263b5fd98ccc2343985',
    messagingSenderId: '270817397728',
    projectId: 'auto-networks',
    storageBucket: 'auto-networks.appspot.com',
    iosBundleId: 'com.example.networkAutomation.RunnerTests',
  );
}
